---
- name: Adding APT Key for Tailscale
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/ubuntu/noble.asc"
    dest: "/etc/apt/keyrings/tailscale.asc"
    mode: "0644"

- name: Adding APT Repository for Tailscale
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/tailscale.asc] https://pkgs.tailscale.com/stable/ubuntu noble main"
    filename: "tailscale"
    state: present

- name: Copying Service Environment File
  ansible.builtin.copy:
    src: "tailscaled.service.env"
    dest: "/etc/default/tailscaled"
    mode: "0644"

- name: Installing Tailscale
  ansible.builtin.apt:
    package:
      - tailscale
    state: present
    update_cache: yes

- name: Enabling and Starting tailscaled.service
  ansible.builtin.systemd_service:
    daemon_reload: yes
    name: tailscaled.service
    enabled: yes
    state: started

- name: Tailscale Now Available
  ansible.builtin.debug:
    msg: "Tailscale installed, use 'tailscale up --auth-key=<your-auth-key>' to connect to your tailnet"
