---
- name: Creating Deployment Directory
  ansible.builtin.file:
    name: "{{ deployment_dir }}"
    state: directory

- name: Templating compose.yaml
  ansible.builtin.template:
    src: "{{ traefik_compose_yaml_template }}"
    dest: "{{ deployment_dir }}/compose.yaml"
  tags:
    - traefik_compose_yaml
  notify: Up traefik

- name: Templating .env
  ansible.builtin.template:
    src: "traefik-env.j2"
    dest: "{{ deployment_dir }}/.env"
    mode: 0600
  tags:
    - traefik_traefik_yml
  notify: Recreate traefik

- name: Templating Static Configuration File
  ansible.builtin.template:
    src: "{{ traefik_traefik_yml_template }}"
    dest: "{{ deployment_dir }}/traefik.yml"
  tags:
    - traefik_traefik_yml
  notify: Recreate traefik

- name: Creating Dynamic Configuration Directory
  ansible.builtin.file:
    name: "{{ deployment_dir }}/conf.d"
    state: directory

- name: Templating middleware-whitelist.yml
  ansible.builtin.template:
    src: "middleware-whitelist.j2.yml"
    dest: "/opt/stacks/traefik/conf.d/middleware-whitelist.yml"
  when: traefik_whitelist_cidrs is defined

- name: Creating Traefik Network
  community.docker.docker_network:
    name: "{{ traefik_network_name }}"
    state: present
