---
services:
  proxy:
    image: traefik:v{{ traefik_version }}
    restart: always
    network_mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Access Docker socket for service discovery
      - "letsencrypt:/letsencrypt"
      - "/opt/stacks/traefik/traefik.yml:/etc/traefik/traefik.yml:ro" # static configuration
      - "/opt/stacks/traefik/conf.d:/etc/traefik/conf.d:ro" # dynamic configuration
    env_file:
      - .env

networks:
  "{{ traefik_network_name }}":
    name: "{{ traefik_network_name }}"

volumes:
  letsencrypt:
