---
- name: Creating Deployment Directory
  ansible.builtin.file:
    name: "/opt/dockge"
    state: directory

- name: Creating Stacks Directory
  ansible.builtin.file:
    name: "/opt/stacks"
    state: directory

- name: Templating compose.yaml
  ansible.builtin.template:
    src: "compose.j2.yaml"
    dest: "/opt/dockge/compose.yaml"

- name: Starting Dockge
  ansible.builtin.command:
    chdir: "/opt/dockge"
    cmd: "docker compose up -d"
